export const FETCH_ALL_CAFE = 'FETCH_ALL_CAFE';
export const FETCH_BY_SEARCH_CAFE = 'FETCH_BY_SEARCH_CAFE';
export const CREATE_CAFE = 'CREATE_CAFE';
export const UPDATE_CAFE = 'UPDATE_CAFE';
export const DELETE_CAFE = 'DELETE_CAFE';

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const FETCH_ALL_EMPLOYEE = 'FETCH_ALL_EMPLOYEE';
export const FETCH_BY_SEARCH_EMPLOYEE = 'FETCH_BY_SEARCH_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
